// Mock data — mirrors real API shapes exactly

export const mockUsers = [
  // Auth accounts
  { id: 1, name: 'Karim Benali', email: 'admin@at.dz', password: 'admin123', role: 'ADMIN', company: null, specialty: null, level: null, available: null, created_at: '2024-01-10T08:00:00Z' },
  { id: 2, name: 'Sofiane Meziane', email: 'dev@at.dz', password: 'dev123', role: 'DEVELOPER', company: 'TechCorp DZ', specialty: null, level: null, available: null, created_at: '2024-02-05T10:30:00Z' },
  { id: 3, name: 'Amira Khelif', email: 'eng@at.dz', password: 'eng123', role: 'ENGINEER', company: null, specialty: 'Réseau & Infrastructure', level: 'SENIOR', available: true, created_at: '2024-01-20T09:15:00Z' },
  { id: 4, name: 'Youcef Ait Saad', email: 'youcef@at.dz', password: 'pass123', role: 'ENGINEER', company: null, specialty: 'Sécurité', level: 'MID', available: true, created_at: '2024-03-01T11:00:00Z' },
  { id: 5, name: 'Lydia Boudali', email: 'lydia@at.dz', password: 'pass123', role: 'DEVELOPER', company: 'StartDZ', specialty: null, level: null, available: null, created_at: '2024-03-15T14:20:00Z' },
  { id: 6, name: 'Farid Ouahmed', email: 'farid@at.dz', password: 'pass123', role: 'ENGINEER', company: null, specialty: 'Base de données', level: 'JUNIOR', available: false, created_at: '2024-04-01T08:45:00Z' },
  { id: 7, name: 'Nadia Zerrouki', email: 'nadia@at.dz', password: 'pass123', role: 'ADMIN', company: null, specialty: null, level: null, available: null, created_at: '2024-01-15T07:30:00Z' },
];

export const mockTickets = [
  { id: 1, title: 'Panne serveur DNS principal', category: 'Infrastructure', status: 'OPEN', developer_id: 2, engineer_id: 3, created_at: '2024-04-10T09:00:00Z'},
  { id: 2, title: 'Certificat SSL expiré sur prod', category: 'Sécurité', status: 'IN_PROGRESS', developer_id: 5, engineer_id: 4, created_at: '2024-04-09T14:30:00Z'},
  { id: 3, title: 'Base de données lente après migration', category: 'Base de données', status: 'AWAITING_CLARIFICATION', developer_id: 2, engineer_id: 6, created_at: '2024-04-08T11:00:00Z'},
  { id: 4, title: 'Erreur 502 sur reverse proxy Nginx', category: 'Infrastructure', status: 'RESOLVED', developer_id: 5, engineer_id: 3, created_at: '2024-04-07T16:00:00Z'},
  { id: 5, title: 'Fuites mémoire application Node.js', category: 'Application', status: 'AUTO_RESOLVED', developer_id: 2, engineer_id: null, created_at: '2024-04-06T10:15:00Z'},
  { id: 6, title: 'Accès VPN impossible depuis bureau Alger', category: 'Réseau', status: 'OPEN', developer_id: 5, engineer_id: 4, created_at: '2024-04-05T08:30:00Z'},
  { id: 7, title: 'Déploiement CD échoué sur branche main', category: 'CI/CD', status: 'IN_PROGRESS', developer_id: 2, engineer_id: 3, created_at: '2024-04-04T13:00:00Z'},
  { id: 8, title: 'Quota disque dépassé sur NFS', category: 'Stockage', status: 'RESOLVED', developer_id: 5, engineer_id: 6, created_at: '2024-04-03T09:45:00Z'},
  { id: 9, title: 'Ralentissement API Gateway en heure de pointe', category: 'Performance', status: 'AWAITING_CLARIFICATION', developer_id: 2, engineer_id: 4, created_at: '2024-04-02T15:30:00Z'},
  { id: 10, title: 'Logs applicatifs non reçus dans ELK', category: 'Monitoring', status: 'AUTO_RESOLVED', developer_id: 5, engineer_id: null, created_at: '2024-04-01T11:20:00Z'},
  { id: 11, title: 'Redémarrage inopiné du load balancer', category: 'Infrastructure', status: 'OPEN', developer_id: 2, engineer_id: 3, created_at: '2024-03-31T08:00:00Z'},
  { id: 12, title: "Timeout SMTP lors de l'envoi d'alertes", category: 'Messagerie', status: 'RESOLVED', developer_id: 5, engineer_id: 4, created_at: '2024-03-30T17:00:00Z'},
  { id: 13, title: 'Panne serveur DNS principal', category: 'Infrastructure', status: 'OPEN', developer_id: 2, engineer_id: 3, created_at: '2024-04-10T09:00:00Z'},
  { id: 14, title: 'Certificat SSL expiré sur prod', category: 'Sécurité', status: 'IN_PROGRESS', developer_id: 5, engineer_id: 4, created_at: '2024-04-09T14:30:00Z'},
  { id: 15, title: 'Base de données lente après migration', category: 'Base de données', status: 'AWAITING_CLARIFICATION', developer_id: 2, engineer_id: 6, created_at: '2024-04-08T11:00:00Z'},
  { id: 16, title: 'Erreur 502 sur reverse proxy Nginx', category: 'Infrastructure', status: 'RESOLVED', developer_id: 5, engineer_id: 3, created_at: '2024-04-07T16:00:00Z'},
  { id: 17, title: 'Fuites mémoire application Node.js', category: 'Application', status: 'AUTO_RESOLVED', developer_id: 2, engineer_id: null, created_at: '2024-04-06T10:15:00Z'},
  { id: 18, title: 'Accès VPN impossible depuis bureau Alger', category: 'Réseau', status: 'OPEN', developer_id: 5, engineer_id: 4, created_at: '2024-04-05T08:30:00Z'},
  { id: 19, title: 'Déploiement CD échoué sur branche main', category: 'CI/CD', status: 'IN_PROGRESS', developer_id: 2, engineer_id: 3, created_at: '2024-04-04T13:00:00Z'},
  { id: 20, title: 'Quota disque dépassé sur NFS', category: 'Stockage', status: 'RESOLVED', developer_id: 5, engineer_id: 6, created_at: '2024-04-03T09:45:00Z'},
  { id: 21, title: 'Ralentissement API Gateway en heure de pointe', category: 'Performance', status: 'AWAITING_CLARIFICATION', developer_id: 2, engineer_id: 4, created_at: '2024-04-02T15:30:00Z'},
  { id: 22, title: 'Logs applicatifs non reçus dans ELK', category: 'Monitoring', status: 'AUTO_RESOLVED', developer_id: 5, engineer_id: null, created_at: '2024-04-01T11:20:00Z'},
  { id: 23, title: 'Redémarrage inopiné du load balancer', category: 'Infrastructure', status: 'OPEN', developer_id: 2, engineer_id: 3, created_at: '2024-03-31T08:00:00Z'},
  { id: 24, title: "Timeout SMTP lors de l'envoi d'alertes", category: 'Messagerie', status: 'RESOLVED', developer_id: 5, engineer_id: 4, created_at: '2024-03-30T17:00:00Z'},
  { id: 25, title: 'Panne serveur DNS principal', category: 'Infrastructure', status: 'OPEN', developer_id: 2, engineer_id: 3, created_at: '2024-04-10T09:00:00Z'},
  { id: 26, title: 'Certificat SSL expiré sur prod', category: 'Sécurité', status: 'IN_PROGRESS', developer_id: 5, engineer_id: 4, created_at: '2024-04-09T14:30:00Z'},
  { id: 27, title: 'Base de données lente après migration', category: 'Base de données', status: 'AWAITING_CLARIFICATION', developer_id: 2, engineer_id: 6, created_at: '2024-04-08T11:00:00Z'},
  { id: 28, title: 'Erreur 502 sur reverse proxy Nginx', category: 'Infrastructure', status: 'RESOLVED', developer_id: 5, engineer_id: 3, created_at: '2024-04-07T16:00:00Z'},
  { id: 29, title: 'Fuites mémoire application Node.js', category: 'Application', status: 'AUTO_RESOLVED', developer_id: 2, engineer_id: null, created_at: '2024-04-06T10:15:00Z'},
  { id: 30, title: 'Accès VPN impossible depuis bureau Alger', category: 'Réseau', status: 'OPEN', developer_id: 5, engineer_id: 4, created_at: '2024-04-05T08:30:00Z'},
  { id: 31, title: 'Déploiement CD échoué sur branche main', category: 'CI/CD', status: 'IN_PROGRESS', developer_id: 2, engineer_id: 3, created_at: '2024-04-04T13:00:00Z'},
  { id: 32, title: 'Quota disque dépassé sur NFS', category: 'Stockage', status: 'RESOLVED', developer_id: 5, engineer_id: 6, created_at: '2024-04-03T09:45:00Z'},
  { id: 33, title: 'Ralentissement API Gateway en heure de pointe', category: 'Performance', status: 'AWAITING_CLARIFICATION', developer_id: 2, engineer_id: 4, created_at: '2024-04-02T15:30:00Z'},
  { id: 34, title: 'Logs applicatifs non reçus dans ELK', category: 'Monitoring', status: 'AUTO_RESOLVED', developer_id: 5, engineer_id: null, created_at: '2024-04-01T11:20:00Z'},
  { id: 35, title: 'Redémarrage inopiné du load balancer', category: 'Infrastructure', status: 'OPEN', developer_id: 2, engineer_id: 3, created_at: '2024-03-31T08:00:00Z'},
  { id: 36, title: "Timeout SMTP lors de l'envoi d'alertes", category: 'Messagerie', status: 'RESOLVED', developer_id: 5, engineer_id: 4, created_at: '2024-03-30T17:00:00Z'},
];

export const mockMisassignments = [
  { id: 1, ticket_id: 3, engineer_id: 6, engineer_name: 'Farid Ouahmed', reason: "L'ingénieur n'a pas les droits d'administration sur les serveurs de base de données de production. La spécialité requise est DBA Senior et non DB Junior.", status: 'PENDING', reported_at: '2024-04-08T12:00:00Z' },
  { id: 2, ticket_id: 6, engineer_id: 4, engineer_name: 'Youcef Ait Saad', reason: "Le problème VPN nécessite un accès aux équipements Cisco ASA, pour lesquels l'ingénieur n'a pas de certification. Réorienter vers un ingénieur réseau certifié.", status: 'PENDING', reported_at: '2024-04-05T09:00:00Z' },
  { id: 3, ticket_id: 2, engineer_id: 4, engineer_name: 'Youcef Ait Saad', reason: 'Assigné à un ingénieur sécurité alors que le renouvellement SSL sur ce CDN est géré par l\'équipe infrastructure.', status: 'REVIEWED', reported_at: '2024-04-09T15:30:00Z' },
  { id: 4, ticket_id: 9, engineer_id: 4, engineer_name: 'Youcef Ait Saad', reason: "Problème de performance API Gateway qui nécessite une expertise en optimisation Nginx/Kong, pas sécurité.", status: 'REASSIGNED', reported_at: '2024-04-02T16:00:00Z' },
];

export const mockKbEntries = [
  { id: 1, source_ticket_id: 5, description: 'Fuites mémoire dans les applications Node.js dues à des event listeners non nettoyés et des closures mal gérées dans des boucles async.', solution: 'Utiliser `--inspect` avec Chrome DevTools pour profiler, identifier les listeners orphelins avec `process.listenerCount()`, et forcer le GC via `global.gc()` en debug mode. En production, implémenter un circuit breaker avec un restart automatique via PM2.', created_at: '2024-04-06T11:00:00Z' },
  { id: 2, source_ticket_id: 10, description: 'Les logs Logstash ne parviennent pas dans Elasticsearch suite à un problème de configuration du pipeline Filebeat.', solution: 'Vérifier le fichier `filebeat.yml`, s\'assurer que l\'output pointe sur le bon port Logstash (5044), et confirmer que les indices dans Kibana correspondent au pattern configuré.', created_at: '2024-04-01T12:30:00Z' },
  { id: 3, source_ticket_id: 4, description: 'Erreur 502 Bad Gateway sur Nginx après montée en charge, causée par le upstream timing out.', solution: 'Augmenter `proxy_read_timeout`, `proxy_connect_timeout` dans la config Nginx. Vérifier la santé des upstreams avec `ng_status`. Activer `keepalive` sur le pool upstream.', created_at: '2024-04-07T17:00:00Z' },
  { id: 4, source_ticket_id: 8, description: 'Quota disque NFS dépassé sur le volume /data/shared à cause de fichiers temporaires de jobs non nettoyés.', solution: 'Identifier avec `du -sh /data/shared/* | sort -h`, supprimer les anciens fichiers tmp, et ajouter un cron job de nettoyage : `find /tmp -type f -mtime +7 -delete`.', created_at: '2024-04-03T10:30:00Z' },
  { id: 5, source_ticket_id: 12, description: 'Timeout SMTP lors de l\'envoi d\'alertes système depuis le serveur de monitoring.', solution: 'Vérifier la configuration Postfix, en particulier `relayhost` et les règles iptables sur le port 587. Tester avec `telnet smtp.example.com 587`. Utiliser un relay SMTP externe si le port est bloqué.', created_at: '2024-03-30T18:00:00Z' },
];

export const mockAiLogs = [
  { id: 1, ticket_id: 5, decision: 'AUTO_RESOLVE', reason: 'Problème identifié dans la base de connaissances avec un score de similarité élevé. Solution appliquée automatiquement.', richesse_score: 0.91, similarite_score: 0.87, duration_ms: 1243, created_at: '2024-04-06T10:30:00Z'},
  { id: 2, ticket_id: 10, decision: 'AUTO_RESOLVE', reason: 'Correspondance exacte trouvée pour la configuration Filebeat/Logstash dans le KB.', richesse_score: 0.88, similarite_score: 0.93, duration_ms: 987, created_at: '2024-04-01T11:45:00Z'},
  { id: 3, ticket_id: 3, decision: 'OPEN_CLARIFICATION', reason: 'Ticket insuffisamment détaillé. L\'IA a demandé des logs supplémentaires et la version exacte de la base de données.', richesse_score: 0.42, similarite_score: 0.31, duration_ms: 2100, created_at: '2024-04-08T11:30:00Z'},
  { id: 4, ticket_id: 9, decision: 'OPEN_CLARIFICATION', reason: 'Plusieurs causes possibles identifiées. Besoin de métriques de latence et de traces distribuées pour affiner le diagnostic.', richesse_score: 0.55, similarite_score: 0.48, duration_ms: 1876, created_at: '2024-04-02T16:00:00Z'},
  { id: 5, ticket_id: 1, decision: 'ESCALATE_DIRECTLY', reason: 'Panne critique niveau infrastructure. Aucune correspondance KB. Escalade directe vers ingénieur Senior.', richesse_score: 0.78, similarite_score: 0.21, duration_ms: 543, created_at: '2024-04-10T09:15:00Z'},
  { id: 6, ticket_id: 2, decision: 'ESCALATE_DIRECTLY', reason: 'Certificat SSL critique en production. Priorité maximale, escalade immédiate sans clarification nécessaire.', richesse_score: 0.82, similarite_score: 0.33, duration_ms: 421, created_at: '2024-04-09T14:45:00Z'},
  { id: 7, ticket_id: 11, decision: 'ESCALATE_DIRECTLY', reason: 'Redémarrage load balancer impacte 100% du trafic. Escalade directe vers l\'équipe infrastructure.', richesse_score: 0.75, similarite_score: 0.18, duration_ms: 389, created_at: '2024-03-31T08:15:00Z'},
  { id: 8, ticket_id: 5, decision: 'AUTO_RESOLVE', reason: 'Problème identifié dans la base de connaissances avec un score de similarité élevé. Solution appliquée automatiquement.', richesse_score: 0.91, similarite_score: 0.87, duration_ms: 1243, created_at: '2024-04-06T10:30:00Z'},
  { id: 9, ticket_id: 10, decision: 'AUTO_RESOLVE', reason: 'Correspondance exacte trouvée pour la configuration Filebeat/Logstash dans le KB.', richesse_score: 0.88, similarite_score: 0.93, duration_ms: 987, created_at: '2024-04-01T11:45:00Z'},
  { id: 10, ticket_id: 3, decision: 'OPEN_CLARIFICATION', reason: 'Ticket insuffisamment détaillé. L\'IA a demandé des logs supplémentaires et la version exacte de la base de données.', richesse_score: 0.42, similarite_score: 0.31, duration_ms: 2100, created_at: '2024-04-08T11:30:00Z'},
  { id: 11, ticket_id: 9, decision: 'OPEN_CLARIFICATION', reason: 'Plusieurs causes possibles identifiées. Besoin de métriques de latence et de traces distribuées pour affiner le diagnostic.', richesse_score: 0.55, similarite_score: 0.48, duration_ms: 1876, created_at: '2024-04-02T16:00:00Z'},
  { id: 12, ticket_id: 1, decision: 'ESCALATE_DIRECTLY', reason: 'Panne critique niveau infrastructure. Aucune correspondance KB. Escalade directe vers ingénieur Senior.', richesse_score: 0.78, similarite_score: 0.21, duration_ms: 543, created_at: '2024-04-10T09:15:00Z'},
  { id: 13, ticket_id: 2, decision: 'ESCALATE_DIRECTLY', reason: 'Certificat SSL critique en production. Priorité maximale, escalade immédiate sans clarification nécessaire.', richesse_score: 0.82, similarite_score: 0.33, duration_ms: 421, created_at: '2024-04-09T14:45:00Z'},
  { id: 14, ticket_id: 11, decision: 'ESCALATE_DIRECTLY', reason: 'Redémarrage load balancer impacte 100% du trafic. Escalade directe vers l\'équipe infrastructure.', richesse_score: 0.75, similarite_score: 0.18, duration_ms: 389, created_at: '2024-03-31T08:15:00Z'},
  { id: 15, ticket_id: 5, decision: 'AUTO_RESOLVE', reason: 'Problème identifié dans la base de connaissances avec un score de similarité élevé. Solution appliquée automatiquement.', richesse_score: 0.91, similarite_score: 0.87, duration_ms: 1243, created_at: '2024-04-06T10:30:00Z'},
  { id: 16, ticket_id: 10, decision: 'AUTO_RESOLVE', reason: 'Correspondance exacte trouvée pour la configuration Filebeat/Logstash dans le KB.', richesse_score: 0.88, similarite_score: 0.93, duration_ms: 987, created_at: '2024-04-01T11:45:00Z'},
  { id: 17, ticket_id: 3, decision: 'OPEN_CLARIFICATION', reason: 'Ticket insuffisamment détaillé. L\'IA a demandé des logs supplémentaires et la version exacte de la base de données.', richesse_score: 0.42, similarite_score: 0.31, duration_ms: 2100, created_at: '2024-04-08T11:30:00Z'},
  { id: 18, ticket_id: 9, decision: 'OPEN_CLARIFICATION', reason: 'Plusieurs causes possibles identifiées. Besoin de métriques de latence et de traces distribuées pour affiner le diagnostic.', richesse_score: 0.55, similarite_score: 0.48, duration_ms: 1876, created_at: '2024-04-02T16:00:00Z'},
  { id: 19, ticket_id: 1, decision: 'ESCALATE_DIRECTLY', reason: 'Panne critique niveau infrastructure. Aucune correspondance KB. Escalade directe vers ingénieur Senior.', richesse_score: 0.78, similarite_score: 0.21, duration_ms: 543, created_at: '2024-04-10T09:15:00Z'},
  { id: 20, ticket_id: 2, decision: 'ESCALATE_DIRECTLY', reason: 'Certificat SSL critique en production. Priorité maximale, escalade immédiate sans clarification nécessaire.', richesse_score: 0.82, similarite_score: 0.33, duration_ms: 421, created_at: '2024-04-09T14:45:00Z'},
  { id: 21, ticket_id: 11, decision: 'ESCALATE_DIRECTLY', reason: 'Redémarrage load balancer impacte 100% du trafic. Escalade directe vers l\'équipe infrastructure.', richesse_score: 0.75, similarite_score: 0.18, duration_ms: 389, created_at: '2024-03-31T08:15:00Z'},
  { id: 22, ticket_id: 5, decision: 'AUTO_RESOLVE', reason: 'Problème identifié dans la base de connaissances avec un score de similarité élevé. Solution appliquée automatiquement.', richesse_score: 0.91, similarite_score: 0.87, duration_ms: 1243, created_at: '2024-04-06T10:30:00Z'},
  { id: 23, ticket_id: 10, decision: 'AUTO_RESOLVE', reason: 'Correspondance exacte trouvée pour la configuration Filebeat/Logstash dans le KB.', richesse_score: 0.88, similarite_score: 0.93, duration_ms: 987, created_at: '2024-04-01T11:45:00Z'},
  { id: 24, ticket_id: 3, decision: 'OPEN_CLARIFICATION', reason: 'Ticket insuffisamment détaillé. L\'IA a demandé des logs supplémentaires et la version exacte de la base de données.', richesse_score: 0.42, similarite_score: 0.31, duration_ms: 2100, created_at: '2024-04-08T11:30:00Z'},
  { id: 25, ticket_id: 9, decision: 'OPEN_CLARIFICATION', reason: 'Plusieurs causes possibles identifiées. Besoin de métriques de latence et de traces distribuées pour affiner le diagnostic.', richesse_score: 0.55, similarite_score: 0.48, duration_ms: 1876, created_at: '2024-04-02T16:00:00Z'},
  { id: 26, ticket_id: 1, decision: 'ESCALATE_DIRECTLY', reason: 'Panne critique niveau infrastructure. Aucune correspondance KB. Escalade directe vers ingénieur Senior.', richesse_score: 0.78, similarite_score: 0.21, duration_ms: 543, created_at: '2024-04-10T09:15:00Z'},
  { id: 27, ticket_id: 2, decision: 'ESCALATE_DIRECTLY', reason: 'Certificat SSL critique en production. Priorité maximale, escalade immédiate sans clarification nécessaire.', richesse_score: 0.82, similarite_score: 0.33, duration_ms: 421, created_at: '2024-04-09T14:45:00Z'},
  { id: 28, ticket_id: 11, decision: 'ESCALATE_DIRECTLY', reason: 'Redémarrage load balancer impacte 100% du trafic. Escalade directe vers l\'équipe infrastructure.', richesse_score: 0.75, similarite_score: 0.18, duration_ms: 389, created_at: '2024-03-31T08:15:00Z'},
];

export const mockAuditLogs = [
  { id: 1, actor_id: 1, actor_type: 'ADMIN', action: 'CREATE_USER', target: 'USER', target_id: 3, created_at: '2024-01-20T09:15:00Z'},
  { id: 2, actor_id: 1, actor_type: 'ADMIN', action: 'ASSIGN_TICKET', target: 'TICKET', target_id: 1, created_at: '2024-04-10T09:30:00Z'},
  { id: 3, actor_id: 3, actor_type: 'ENGINEER', action: 'RESOLVE_TICKET', target: 'TICKET', target_id: 4, created_at: '2024-04-07T17:30:00Z'},
  { id: 4, actor_id: 2, actor_type: 'DEVELOPER', action: 'CREATE_TICKET', target: 'TICKET', target_id: 11, created_at: '2024-03-31T08:00:00Z'},
  { id: 5, actor_id: 1, actor_type: 'ADMIN', action: 'DELETE_USER', target: 'USER', target_id: 99, created_at: '2024-03-28T15:00:00Z'},
  { id: 6, actor_id: 4, actor_type: 'ENGINEER', action: 'REPORT_MISASSIGNMENT', target: 'TICKET', target_id: 6, created_at: '2024-04-05T09:00:00Z'},
  { id: 7, actor_id: 1, actor_type: 'ADMIN', action: 'REASSIGN_TICKET', target: 'MISASSIGNMENT', target_id: 4, created_at: '2024-04-03T11:00:00Z'},
  { id: 8, actor_id: 5, actor_type: 'DEVELOPER', action: 'CREATE_TICKET', target: 'TICKET', target_id: 6, created_at: '2024-04-05T08:30:00Z'},
  { id: 9, actor_id: 7, actor_type: 'ADMIN', action: 'UPDATE_USER', target: 'USER', target_id: 6, created_at: '2024-04-01T10:00:00Z'},
  { id: 10, actor_id: 3, actor_type: 'ENGINEER', action: 'RESOLVE_TICKET', target: 'TICKET', target_id: 7, created_at: '2024-04-04T18:00:00Z'},
  { id: 11, actor_id: 1, actor_type: 'ADMIN', action: 'CREATE_USER', target: 'USER', target_id: 3, created_at: '2024-01-20T09:15:00Z'},
  { id: 12, actor_id: 1, actor_type: 'ADMIN', action: 'ASSIGN_TICKET', target: 'TICKET', target_id: 1, created_at: '2024-04-10T09:30:00Z'},
  { id: 13, actor_id: 3, actor_type: 'ENGINEER', action: 'RESOLVE_TICKET', target: 'TICKET', target_id: 4, created_at: '2024-04-07T17:30:00Z'},
  { id: 14, actor_id: 2, actor_type: 'DEVELOPER', action: 'CREATE_TICKET', target: 'TICKET', target_id: 11, created_at: '2024-03-31T08:00:00Z'},
  { id: 15, actor_id: 1, actor_type: 'ADMIN', action: 'DELETE_USER', target: 'USER', target_id: 99, created_at: '2024-03-28T15:00:00Z'},
  { id: 16, actor_id: 4, actor_type: 'ENGINEER', action: 'REPORT_MISASSIGNMENT', target: 'TICKET', target_id: 6, created_at: '2024-04-05T09:00:00Z'},
  { id: 17, actor_id: 1, actor_type: 'ADMIN', action: 'REASSIGN_TICKET', target: 'MISASSIGNMENT', target_id: 4, created_at: '2024-04-03T11:00:00Z'},
  { id: 18, actor_id: 5, actor_type: 'DEVELOPER', action: 'CREATE_TICKET', target: 'TICKET', target_id: 6, created_at: '2024-04-05T08:30:00Z'},
  { id: 19, actor_id: 7, actor_type: 'ADMIN', action: 'UPDATE_USER', target: 'USER', target_id: 6, created_at: '2024-04-01T10:00:00Z'},
  { id: 20, actor_id: 3, actor_type: 'ENGINEER', action: 'RESOLVE_TICKET', target: 'TICKET', target_id: 7, created_at: '2024-04-04T18:00:00Z'},
  { id: 21, actor_id: 1, actor_type: 'ADMIN', action: 'CREATE_USER', target: 'USER', target_id: 3, created_at: '2024-01-20T09:15:00Z'},
  { id: 22, actor_id: 1, actor_type: 'ADMIN', action: 'ASSIGN_TICKET', target: 'TICKET', target_id: 1, created_at: '2024-04-10T09:30:00Z'},
  { id: 23, actor_id: 3, actor_type: 'ENGINEER', action: 'RESOLVE_TICKET', target: 'TICKET', target_id: 4, created_at: '2024-04-07T17:30:00Z'},
  { id: 24, actor_id: 2, actor_type: 'DEVELOPER', action: 'CREATE_TICKET', target: 'TICKET', target_id: 11, created_at: '2024-03-31T08:00:00Z'},
  { id: 25, actor_id: 1, actor_type: 'ADMIN', action: 'DELETE_USER', target: 'USER', target_id: 99, created_at: '2024-03-28T15:00:00Z'},
  { id: 26, actor_id: 4, actor_type: 'ENGINEER', action: 'REPORT_MISASSIGNMENT', target: 'TICKET', target_id: 6, created_at: '2024-04-05T09:00:00Z'},
  { id: 27, actor_id: 1, actor_type: 'ADMIN', action: 'REASSIGN_TICKET', target: 'MISASSIGNMENT', target_id: 4, created_at: '2024-04-03T11:00:00Z'},
  { id: 28, actor_id: 5, actor_type: 'DEVELOPER', action: 'CREATE_TICKET', target: 'TICKET', target_id: 6, created_at: '2024-04-05T08:30:00Z'},
  { id: 29, actor_id: 7, actor_type: 'ADMIN', action: 'UPDATE_USER', target: 'USER', target_id: 6, created_at: '2024-04-01T10:00:00Z'},
  { id: 30, actor_id: 3, actor_type: 'ENGINEER', action: 'RESOLVE_TICKET', target: 'TICKET', target_id: 7, created_at: '2024-04-04T18:00:00Z'},
];

export const mockNotifications = [
  { id: 1, message: 'Nouveau signalement sur le ticket #6 par Youcef Ait Saad.', read: false, created_at: '2024-04-05T09:01:00Z' },
  { id: 2, message: 'Le ticket #1 a été escaladé directement par l\'IA.', read: false, created_at: '2024-04-10T09:16:00Z' },
  { id: 3, message: 'Création d\'un nouvel utilisateur ingénieur : Farid Ouahmed.', read: true, created_at: '2024-04-01T08:50:00Z' },
  { id: 4, message: 'Le ticket #5 a été résolu automatiquement par l\'IA.', read: true, created_at: '2024-04-06T11:01:00Z' },
];
